name: tray_manager_example
description: tray_manager through its 0.5.x compatible API.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  tray_manager:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - images/tray_icon.png
    - images/tray_icon_original.png
