name: tray_manager
description: This plugin allows Flutter desktop apps to define a system tray icon.
version: 0.6.1
homepage: https://github.com/leanflutter/tray_manager

platforms:
  linux:
  macos:
  windows:

topics:
  - tray
  - tray-manager
  - system-tray

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  nativeapi: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
